name: Teste de API com Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - List files (verifica a estrutura)
        run: |
          echo "Estrutura do repositório:"
          ls -R
          echo "Caminho do environment:"
          ls collections/environment/dev.environment.json || echo "Arquivo não encontrado!"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run API Tests
        run: |
          mkdir -p reports/newman
          newman run collections/api-tests.json \
            --environment collections/environment/dev.environment.json \
            --reporters cli,html \
            --reporter-html-export reports/newman/report.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Newman Test Report
          path: reports/newman/report.html